### ISSUE TITLE
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

### ISSUE THREAD

**Issue by ellermister** [JiaPai12138/Crossfirer#31]
```
========请在游戏结束前保持窗口========

Traceback (most recent call last):
  File "d:\development\environment\python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "d:\development\environment\python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "AI_M_BOT_N.py", line 20, in <module>
  File "D:\Program Files\AI-M-BOT\lib\AI_main.py", line 7, in <module AI_main>
  File "D:\Program Files\AI-M-BOT\lib\darknet_yolo34.py", line 1, in <module darknet_yolo34>
  File "D:\Program Files\AI-M-BOT\lib\two_class_threat.py", line 1, in <module two_class_threat>
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

========神经自瞄程序已停止运行========
```

**Comment by JiaPai12138** [comment]
你没把环境dll放进去

**Comment by JiaPai12138** [comment]
> [如果提示缺少dll文件，请下载[lib.7z](https://github.com/JiaPai12138/Crossfirer/releases/download/ex_v2.5.6/lib.7z)并解压然后将lib文件夹移动至安装目录下
