### ISSUE TITLE
神经自瞄启动失败、报错问题

### ISSUE THREAD

**Issue by ZRong-Liu** [JiaPai12138/Crossfirer#35]
活动代码页: 936
========请在游戏结束前保持窗口========

Traceback (most recent call last):
  File "d:\development\environment\python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "d:\development\environment\python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "AI_M_BOT_N.py", line 20, in <module>
  File "D:\Program Files\AI-M-BOT\lib\AI_main.py", line 7, in <module AI_main>
  File "D:\Program Files\AI-M-BOT\lib\darknet_yolo34.py", line 1, in <module darknet_yolo34>
  File "D:\Program Files\AI-M-BOT\lib\two_class_threat.py", line 1, in <module two_class_threat>
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

========神经自瞄程序已停止运行========

请按任意键继续. . .

**Comment by JiaPai12138** [comment]
没把依赖包放进去

**Comment by JiaPai12138** [comment]
https://github.com/AI-M-BOT/CVGO_Release
